# Generated by Django 5.1.4 on 2025-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="short_url",
            field=models.CharField(
                blank=True, help_text="URL generated from url shortener", null=True
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="short_url_id",
            field=models.IntegerField(
                blank=True, help_text="Unique ID linked to shortened URL", null=True
            ),
        ),
    ]
