from django.db import models

from shortly.authentication.models import User
from shortly.common.models import AbstractBase


class Link(AbstractBase):
    """Stores links generated by a User."""

    link = models.CharField()
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="user_links",
    )
    short_url = models.CharField()
    short_url_id = models.IntegerField()
