# Generated by Django 5.1.4 on 2024-12-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
            ),
        ),
    ]
