# Generated by Django 5.1.4 on 2025-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_token",
            field=models.CharField(blank=True, null=True),
        ),
    ]
